### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by sikoushixinyou** [mimicji/FlowMatrix#1]
Hello ! I am very interested in your work.
When I make the project, the following error message appeared：

/usr/bin/ld: src/TraceLoader//TraceLoader.o: in function `acorn_obj::TaintRule::TaintRule()':
/home/kaihang/project/FlowMatrix/FMDynamic/..//libFlowMatrix/include/acorns_obj.pb.h:1115: undefined reference to `acorn_obj::TaintRule::TaintRule(google::protobuf::Arena*)'
collect2: error: ld returned 1 exit status

How should i fix this error？ Thank you !

**Comment by mimicji** [comment]
Hi,

I found that the problem was that some subdirectories did not get cleaned up correctly. I have fixed this issue in the [commit ae077b9](https://github.com/mimicji/FlowMatrix/commit/ae077b938ef6baa311ac7a871ded260904c734b8). 
Now, you may make a git pull, run `make clean` and remake FlowMatrix.

Thanks for your interest in our work.
Kaihang
